//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;
namespace KPFF.Web
{


    public partial class Default
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected TextBox txtUserName { get; set; }
        protected Label lblError { get; set; }
        protected TextBox txtPassword { get; set; }
        protected CheckBox cbRememberMe { get; set; }
    }
}
